let noID;let tamanho;let esquerda=document.getElementById("Esquerda");let direita=document.getElementById("Direita");let cima=document.getElementById("Cima");let baixo=document.getElementById("Baixo");let nomeCidade=document.getElementById("nomeCidade");let idVideo=document.querySelector(".ID");let topicoVid=document.getElementById("topico");let contAside=document.getElementById("addCont");let expandAberto=!1;let verRand;let still;let versao=0;let contMapa=document.getElementById("contMapa");let mapa=document.getElementById("mapa");let currentTopic=null;let nomeNull=document.getElementById("nomeNull");let topicNull=document.getElementById("topicNull");let cidNull=document.getElementById("cidNull");let elemCidade=[];let topicButtons=[];let conteudoAside = document.getElementById("conteudo_Aside");let butTopic;let nomeMapa;let contCidMapa;let butTopicTexto;fetch('jsonGeral.json').then(response=>response.json()).then(data=>{tamanho=data.length;do{noID=Math.floor(Math.random()*tamanho)}while(data[noID].Versao===null);verAvail(data,noID);esquerda.addEventListener("click",function(){versao=0;noID=noID-1;if(noID<0){noID=tamanho;noID=noID-1}
    fecharAside();verAvail(data,noID)});direita.addEventListener("click",function(){versao=0;noID++;if(noID>=tamanho){noID=0}
    fecharAside();verAvail(data,noID)});cima.addEventListener("click",function(){versao=0;if(noID<0){noID=tamanho;noID=noID-1}else if(data[noID].Cidade==="Ândria"||data[noID].Cidade==="Zora"){noID=noID+7}else if(data[noID].Cidade==="Pentesiléia"){noID=noID+3}else if(data[noID].Cidade==="Berenice"||data[noID].Cidade==="Isidora"){noID=noID-1}else if((noID+1)%5===0){noID=noID+11}else if(data[noID].Cidade==="Zaíra"){noID=noID+3}else{noID=noID-4}
    fecharAside();verAvail(data,noID)});baixo.addEventListener("click",function(){versao=0;if(data[noID].Cidade==="Berenice"){noID=0}else if(data[noID].Cidade==="Raíssa"||data[noID].Cidade==="Tamara"){noID=noID-7}else if(data[noID].Cidade==="Marósia"||data[noID].Cidade==="Dorotéia"){noID=noID-3}else if(data[noID].Cidade==="Teodora"||data[noID].Cidade==="Diomira"){noID++}else if(noID%5===0&&data[noID].Cidade!=="Dorotéia"){noID=noID-11}else{noID=noID+4}
    fecharAside();verAvail(data,noID)});let maxVersoes=0;for(let w=0;w<data.length;w++){if(data[w].Versao&&data[w].Versao.length>maxVersoes){maxVersoes=data[w].Versao.length}}
    let maximo=document.getElementById("maxFilmes");maximo.innerText=maxVersoes;for(let m=0;m<tamanho;m++){contCidMapa=document.createElement("div");contCidMapa.classList.add("contCidMapa");contMapa.appendChild(contCidMapa);let versaoCount=data[m].Versao?data[m].Versao.length:0;let minOpacity=0;let maxOpacity=0.9;let opacity=versaoCount/maxVersoes;opacity=Math.max(minOpacity,Math.min(opacity,maxOpacity));contCidMapa.style.backgroundColor=`rgba(255, 255, 255, ${opacity})`;if(opacity>0.7){contCidMapa.style.color="black"}else{contCidMapa.style.color="white"}
        nomeMapa=document.createElement("p");nomeMapa.classList.add("nMapa");nomeMapa.innerText=data[m].Cidade;contCidMapa.appendChild(nomeMapa);elemCidade.push({el:contCidMapa,topico:data[m].Topico});contCidMapa.addEventListener("click",function(){versao=0;noID=m;fecharMapa();verAvail(data,noID)})}
    for(let t=0;t<tamanho;t=t+=5){let butTopic=document.createElement("div");butTopic.classList.add("butTopic");butTopicTexto=document.createElement("p");butTopic.appendChild(butTopicTexto);butTopicTexto.innerText=data[t].Topico;document.getElementById("filtroTopico").appendChild(butTopic);topicButtons.push(butTopic)}
    topicButtons.forEach((button)=>{button.addEventListener("click",function(){const topicoAtual=button.innerText;if(currentTopic===topicoAtual){topicButtons.forEach(btn=>btn.classList.remove("topSel"));currentTopic=null;elemCidade.forEach((city,index)=>{const versaoCount=data[index].Versao?data[index].Versao.length:0;let baseOpacity=versaoCount/maxVersoes;city.el.style.backgroundColor=`rgba(255, 255, 255, ${baseOpacity})`;city.el.style.color=baseOpacity>0.7?"black":"white"})}else{currentTopic=topicoAtual;topicButtons.forEach(btn=>btn.classList.remove("topSel"));button.classList.add("topSel");elemCidade.forEach((city,index)=>{const versaoCount=data[index].Versao?data[index].Versao.length:0;let baseOpacity=versaoCount/maxVersoes;let highlightOpacity=Math.min(baseOpacity+0.4,1);if(city.topico===topicoAtual){city.el.style.backgroundColor=`rgba(181, 197, 255, ${highlightOpacity})`;city.el.style.color=highlightOpacity>0.7?"black":"white";city.el.classList.add("corCidTopic")}else{city.el.style.backgroundColor=`rgba(255, 255, 255, ${baseOpacity})`;city.el.style.color=baseOpacity>0.7?"black":"white"}})}})})});let butMapa=document.getElementById("butMapa");let mapaAberto=!1;butMapa.addEventListener("click",function(){if(mapaAberto===!1){mapa.style.cssText=" transition: translate 0.5s ease-out, overlay 0.5s ease-out, display 0.5s ease-out allow-discrete;\n"+"translate: 0 0;"
    mapa.style.visibility="visible";mapaAberto=!0}else{fecharMapa()}});let fecharMapa_but=document.getElementById("fechar");fecharMapa_but.addEventListener("click",function(){fecharMapa()});function fecharMapa(){mapa.style.cssText=" transition: translate 0.6s ease-out, overlay 0.6s ease-out, display 0.6s ease-out allow-discrete;\n"+"translate: 0 100vh"
    mapa.style.visibility="hidden";mapaAberto=!1}
function verAvail(data,noID){contAside.innerHTML="";video.pause();imgPausa.src="icons/play.png";vid_paused=!0;barraControl.style.width="0";if(data[noID].Versao===null){nomeNull.innerText=data[noID].Cidade;topicNull.innerText=data[noID].Topico;video.style.cssText="display:none";idVideo.innerText="Id: 0000";tirarShow();cidadeNull()}else{cidadeAvail();video.style.cssText="display:block";verRand=data[noID].Versao[versao].ID;video.poster=data[noID].Versao[versao].LinkStill;video.src=data[noID].Versao[versao].Link;idVideo.innerText=verRand;console.log(versao);for(let v=0;v<data[noID].Versao.length;v++){let divVersao=document.createElement("section");contAside.appendChild(divVersao);let titulo=document.createElement("h3");divVersao.appendChild(titulo);titulo.innerText=data[noID].Versao[v].Titulo;let infoVer=document.createElement("div");infoVer.classList.add("infoVer");divVersao.appendChild(infoVer);for(let i=0;i<data[noID].Versao[v].Autores.length;i++){let nome=document.createElement("p");nome.classList.add("autores");infoVer.appendChild(nome);nome.innerText=data[noID].Versao[v].Autores[i]}
    let infoExpand=document.createElement("div");divVersao.appendChild(infoExpand);infoExpand.classList.add("infoExpand");still=document.createElement("img");infoExpand.appendChild(still);still.title="Ver Filme";still.classList.add("still");still.style.cursor="pointer";still.style.zIndex="300";let nStill=1;still.src= data[noID].Versao[v].LinkStill
    still.addEventListener("click",function(){versao=v;video.paused;imgPausa.src="icons/play.png";vid_paused=!0;barraControl.style.width="0";verAvail(data,noID)});let sinopse=document.createElement("p");infoExpand.appendChild(sinopse);sinopse.classList.add("sinopse","texto");sinopse.innerText=data[noID].Versao[v].Sinopse;let infoBottom=document.createElement("div");divVersao.appendChild(infoBottom);infoBottom.classList.add("infoBottom");let ID=document.createElement("p");infoBottom.appendChild(ID);ID.classList.add("ID");ID.innerText="2022";let expandir=document.createElement("p");infoBottom.appendChild(expandir);expandir.classList.add("expandir");expandir.innerText="Saber Mais";expandir.addEventListener("click",function(){if(expandAberto===!1){infoExpand.style.cssText="display:block";expandAberto=!0;expandir.innerText="Colapsar"}else{infoExpand.style.cssText="display:none";expandir.innerText="Saber Mais";expandAberto=!1}})}}
    nomeCidade.innerText=data[noID].Cidade;topicoVid.innerText=data[noID].Topico}
function cidadeNull(){cidNull.classList.add("show");fecharAside();video.pause();video.src="";imgPausa.src="icons/play.png";vid_paused=!0;barraControl.style.width="0";aside.style.display="none";butVer.style.visibility="hidden";slider.style.display="none";sliderAberto=!1;som.style.visibility="hidden";butMapa.style.cssText="margin-left:2vw";imgPausa.style.display="none";barraProg.style.display="none";barraControl.style.display="none"}
function cidadeAvail(){cidNull.classList.remove("show");aside.style.display="block";butVer.style.visibility="visible";som.style.visibility="visible";butMapa.style.cssText="margin-left:1vw";imgPausa.style.display="block";barraProg.style.display="block";barraControl.style.display="block"}
function playFunction(){if(vid_paused===!1){video.pause();imgPausa.src="icons/play.png";vid_paused=!0}else if(vid_paused===!0){video.play();imgPausa.src="icons/pausa.png";vid_paused=!1}}
let botao_play=document.getElementById("botao_pausa");let video=document.querySelector("video");let vid_paused=!1;let imgPausa=document.getElementById("pausa");botao_play.addEventListener("click",function(){playFunction();});window.addEventListener("keydown",function(i){if(i.keyCode===32){playFunction();addShow();}});let barraProg=document.getElementById("barraProg");let barraControl=document.getElementById("barraControl");video.addEventListener("timeupdate",function(){const valor=(video.currentTime/video.duration)*100;barraControl.style.width=valor+"%"});barraProg.addEventListener("click",function(e){let rect=barraProg.getBoundingClientRect();let clickX=e.clientX-rect.left;let width=rect.width;let clickRatio=clickX/width;video.currentTime=clickRatio*video.duration});let myTimeout=setTimeout(tirarShow,1500);let setas=document.querySelectorAll(".setas");let butBaixo=document.querySelectorAll(".but_baixo");function tirarShow(){imgPausa.classList.remove("show");barraProg.classList.remove("show");botao_play.style.cursor="none";setas.forEach(element=>{element.classList.remove("show")});butBaixo.forEach(element=>{element.classList.remove("show")})}
function addShow(){clearTimeout(myTimeout);imgPausa.classList.add("show");barraProg.classList.add("show");barraProg.style.display="block";myTimeout=setTimeout(tirarShow,1500);botao_play.style.cursor="pointer";setas.forEach(element=>{element.classList.add("show")});butBaixo.forEach(element=>{element.classList.add("show")})}
window.addEventListener("mousemove",(event)=>{addShow()});window.addEventListener("click",(event)=>{addShow()});let sliderAberto=!1;let slider=document.querySelector(".slider");let som=document.getElementById("volume");som.addEventListener("click",function(){if(sliderAberto===!1){slider.style.display="block";sliderAberto=!0}else{slider.style.display="none";sliderAberto=!1}});slider.addEventListener("input",(e)=>{video.volume=e.currentTarget.value/100});let butVer=document.getElementById("butVersao");let aside=document.querySelector("aside");let asideAberto=!1;butVer.addEventListener("click",function(){if(asideAberto===!1){aside.style.cssText="width:35vw;\n"+"    transition: width 0.4s linear;";conteudoAside.style.cssText=" transition: translate 0.5s ease-out, overlay 0.5s ease-out, display 0.5s ease-out allow-discrete;\n"+"    translate: 0 0;"
    asideAberto=!0}else{fecharAside()}});let fecharVer=document.getElementById("fecharVer");fecharVer.addEventListener("click",function(){fecharAside()});let translateValue=-30;function fecharAside(){aside.style.cssText="width:0;\n"+"transition: width 0.4s linear;";conteudoAside.style.cssText=" transition: translate 0.5s ease-out, overlay 0.5s ease-out, display 0.5s ease-out allow-discrete;\n"+"translate:"+translateValue+"0;"
    asideAberto=!1}
let fecharAbout=document.getElementById("fecharAbout");let About=document.getElementById("contAbout");let aboutAberto=!1;let butAbout=document.getElementById("butAbout");fecharAbout.addEventListener("click",function(){if(aboutAberto===!1){About.style.display="block";aboutAberto=!0}else{About.style.display="none";aboutAberto=!1}});butAbout.addEventListener("click",function(){About.style.display="block";aboutAberto=!0});let phoneBg=document.getElementById("phoneBg")
phoneBg.addEventListener("click",function(){phoneBg.style.display="none"});function myFunction(x){if(x.matches){translateValue=-47}else{translateValue=-27}}
var x=window.matchMedia("(max-width: 1000px)");myFunction(x);x.addEventListener("change",function(){myFunction(x)})
